version: '3'
services:
  postgres_gympoint_api:
    image: postgres:11
    postgres_gympoint_api: 'postgres_gympoint_api'
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - TZ=GMT
    ports:
      - 5432:5432
  redis_gympoint_api:
    image: redis:alpine
    redis_gympoint_api: 'redis_gympoint_api'
    ports:
      - 6379:6379
